# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: akari michitani
description: > # this means to ignore newlines until "baseurl:"
  道谷明里のアート作品ポートフォリオ
keywords: > # this means to ignore newlines until "baseurl:"
  道谷明里、アート、作品、ポートフォリオ、芸術、akari michitani。
url: "https://akarimichitani.github.io" # the base hostname & protocol for your site #footer built by link

# baseurl: ""
permalink: /:title/

#color scheme - Purple theme
color-1: '#555'
color-2: '#998e8e'

#Endless-River theme - remove the '#'
#color-1: '#155799'
#color-2: '#159957'

#footer icons
# f:   # facebook username
t: "@kari_michitani"  # twitter handle
i: "michitan1" # instagram username
# y:  # youtube channel

# Build settings
markdown: kramdown
sass:
    style: compressed

#Other
# analytics: ''

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Adding front matter to static files
defaults:
  - scope:
      path: "dev/img"
    values:
      image: true
